version: '3.8'

services:
  postgres:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=partiguiden
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=partiguiden-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data/pgdata
